name: τ-Crystal Verify
description: Verify manifests/artifacts with τ-Crystal (Lean-backed)
author: tau-crystal
branding:
  color: blue
  icon: check
inputs:
  manifest:
    description: Path to manifest JSON to verify
    required: true
  fail-on-mismatch:
    description: "If true, fail job when verification != ok"
    default: "true"
outputs:
  status:
    description: Verification status (ok|mismatch|error)
    value: ${{ steps.verify.outputs.status }}
runs:
  using: composite
  steps:
    - name: Setup Lean
      shell: bash
      run: bash scripts/ci/setup_lean.sh
    - id: verify
      name: Verify
      shell: bash
      run: bash scripts/action_verify.sh "${{ inputs.manifest }}" "${{ inputs.fail-on-mismatch }}"
