name: tau-crystal-ci
on: [push, pull_request]

jobs:
  win-ci:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.x' }

      # Install Git for Windows Bash path (already present) and elan/lean
      - name: Install elan (Lean toolchain)
        run: |
          curl -L https://raw.githubusercontent.com/leanprover/elan/master/elan-init.ps1 -o elan-init.ps1
          pwsh -ExecutionPolicy Bypass -File elan-init.ps1 -NoPrompt
          echo "$env:USERPROFILE\.elan\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          elan default (Get-Content -Raw lean-toolchain)
          lean --version
          lake --version

      - name: Assure (PowerShell harness)
        run: powershell -ExecutionPolicy Bypass -File .\assure.ps1

      - name: Assure (Bash harness)
        shell: bash
        run: |
          set -euo pipefail
          ./assure.sh

      - name: Linear size probe (Bash)
        shell: bash
        run: |
          set -euo pipefail
          ./tools/verify_linear.sh | tee linear_size.csv

      - name: Linear reps probe (Bash)
        shell: bash
        run: |
          set -euo pipefail
          ./tools/verify_linear_reps.sh | tee linear_reps.csv

      - name: Upload probe CSVs
        uses: actions/upload-artifact@v4
        with:
          name: probes
          path: |
            linear_size.csv
            linear_reps.csv
