#!/usr/bin/env bash
set -euo pipefail; set +H; umask 022; export LC_ALL=C LANG=C
ROOT="${1:-analysis/_runs}"; STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
OUT="$ROOT/bordism_$STAMP"; mkdir -p "$OUT/types" "$OUT/morphisms" ".tau_ledger/_schemas"
TREG="$OUT/types/registry.csv"; MREG="$OUT/morphisms/registry.csv"; J="$OUT/bordism_min.json"
: > "$TREG"; : > "$MREG"; : > "$J"
printf "%s\n" "stratum_id,name,dim,orientation,framing" >> "$TREG"
printf "%s\n" "O0,point,0,oriented,framed" >> "$TREG"
printf "%s\n" "O1,interval,1,oriented,framed" >> "$TREG"
printf "%s\n" "O2,surface,2,oriented,string" >> "$TREG"
printf "%s\n" "morphism_id,source,target,monoidal,label" >> "$MREG"
printf "%s\n" "fuse01,O1+O1,O1,⊗,defect_fusion" >> "$MREG"
printf "%s\n" "cut01,O2+O1,O2,⊗,cut" >> "$MREG"
printf "%s\n" "{" >> "$J"
printf "%s\n" "  \"strata\": [" >> "$J"
printf "%s\n" "    {\"id\":\"O0\",\"name\":\"point\",\"dim\":0,\"orientation\":\"oriented\",\"framing\":\"framed\"}," >> "$J"
printf "%s\n" "    {\"id\":\"O1\",\"name\":\"interval\",\"dim\":1,\"orientation\":\"oriented\",\"framing\":\"framed\"}," >> "$J"
printf "%s\n" "    {\"id\":\"O2\",\"name\":\"surface\",\"dim\":2,\"orientation\":\"oriented\",\"framing\":\"string\"}" >> "$J"
printf "%s\n" "  ]," >> "$J"
printf "%s\n" "  \"morphisms\": [" >> "$J"
printf "%s\n" "    {\"id\":\"fuse01\",\"source\":\"O1+O1\",\"target\":\"O1\",\"monoidal\":\"⊗\",\"label\":\"defect_fusion\"}," >> "$J"
printf "%s\n" "    {\"id\":\"cut01\",\"source\":\"O2+O1\",\"target\":\"O2\",\"monoidal\":\"⊗\",\"label\":\"cut\"}" >> "$J"
printf "%s\n" "  ]" >> "$J"
printf "%s\n" "}" >> "$J"
echo "[ok] typed bordism → $J"
