name: Langlands Lab CI
on: [push, pull_request]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python (python -> python3)
        run: sudo apt-get update && sudo apt-get install -y python3 python-is-python3

      - name: Adele snapshot
        run: bash scripts/langlands/lab.sh adele .

      - name: L(1) and rank(.tau_ledger)
        run: |
          bash scripts/langlands/lab.sh L 1 .tau_ledger
          bash scripts/langlands/lab.sh rank .tau_ledger

      - name: Parameter sweep (scan modularity)
        id: scan
        run: |
          SCAN_PATH=$(python scripts/langlands/scan_modularity.py ".tau_ledger" ".tau_ledger/demo")
          echo "path=${SCAN_PATH}" >> "$GITHUB_OUTPUT"
          echo "scan_path=$SCAN_PATH"

      - name: Pick best (n,s,t)
        id: best
        run: |
          python scripts/langlands/emit_best.py "${{ steps.scan.outputs.path }}"
        shell: bash

      - name: Hecke/Theta with chosen params
        run: |
          echo "Using n=${{ steps.best.outputs.BEST_N }} s=${{ steps.best.outputs.BEST_S }} t=${{ steps.best.outputs.BEST_T }} (Delta~${{ steps.best.outputs.BEST_DELTA }})"
          bash scripts/langlands/lab.sh hecke "${{ steps.best.outputs.BEST_N }}" .tau_ledger
          bash scripts/langlands/lab.sh theta "${{ steps.best.outputs.BEST_S }}" "${{ steps.best.outputs.BEST_T }}" .tau_ledger/demo

      - name: Modularity assertion (fail if not within tol)
        env:
          TOL: '1e-3'
        run: |
          bash scripts/langlands/lab.sh modular "${{ steps.best.outputs.BEST_N }}" .tau_ledger/demo .tau_ledger "$TOL"
      - name: Bash reciprocity (strict)
        run: bash scripts/langlands/reciprocity.sh .tau_ledger .tau_ledger/demo 1000
      - name: Bash reciprocity (soft report)
        run: bash scripts/langlands/reciprocity.sh .tau_ledger .tau_ledger/demo 1000 --soft

      - name: Bash reciprocity verify (gate)
        run: bash scripts/langlands/reciprocity_verify.sh 1000 .tau_ledger .tau_ledger/demo
      - name: Upload reciprocity artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reciprocity-best
          path: |
            analysis/reciprocity_best.tsv
            analysis/reciprocity_best.env
            analysis/bash_theta_scan.tsv
      - name: Normalize artifact + plot
        run: bash scripts/langlands/artifact_normalize.sh && bash scripts/langlands/plots_write.sh
      - name: Upload L-data normalized artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ldata-normalized
          path: |
            analysis/normalized/*.norm.json
            analysis/plots/status.svg
      - name: Double-zero scan
        run: |
          bash scripts/langlands/double_zero_scan.sh
          bash scripts/langlands/double_zero_refine.sh
      - name: Upload double-zero artifacts
        uses: actions/upload-artifact@v4
        with:
          name: double-zero-artifacts
          path: |
            analysis/double_zero_ords.tsv
            analysis/double_zero_clusters.tsv
            analysis/double_zero_refined.tsv
            analysis/plots/doubles.svg
            analysis/plots/doubles_refined.svg
