-- Auto-generated by scripts/fermion/init.sh
namespace TauCrystal

structure Fermion where
  name    : String
  index   : Int
  massGeV : Float
  logZ    : Float
  tags    : String

def fermions : List Fermion :=
  [
    { name := "electron", index := 54, massGeV := 0.00051099895, logZ := -8.24, tags := "2*3^3" },
    { name := "muon", index := 405, massGeV := 0.1056583755, logZ := -4.59, tags := "3^4*5" },
    { name := "tau", index := 1485, massGeV := 1.77686, logZ := -2.71, tags := "3*5*99" },
    { name := "up", index := 72, massGeV := 0.0023, logZ := -7.56, tags := "2^3*3^2" },
    { name := "down", index := 90, massGeV := 0.0048, logZ := -7.11, tags := "2*3^2*5" },
    { name := "strange", index := 324, massGeV := 0.095, logZ := -5.60, tags := "2^2*3^4" },
    { name := "charm", index := 1215, massGeV := 1.27, logZ := -3.10, tags := "3^5*5" },
    { name := "bottom", index := 3645, massGeV := 4.18, logZ := -2.30, tags := "3^6*5" },
    { name := "top", index := 4095, massGeV := 172.76, logZ := -0.10, tags := "3*5*273" },
    { name := "nu_e", index := 6, massGeV := 0.000001, logZ := -9.00, tags := "2*3   " },
    { name := "nu_mu", index := 18, massGeV := 0.000008, logZ := -8.40, tags := "2*3^2" },
    { name := "nu_tau", index := 30, massGeV := 0.000050, logZ := -7.80, tags := "2*3*5" }  ]

end TauCrystal
