#!/usr/bin/env bash
set -euo pipefail; set +H; umask 022; export LC_ALL=C LANG=C
ts="$(date -u +%Y%m%dT%H%M%SZ)"
out=".tau_ledger/freed/factorization_gate_${ts}.json"
mkdir -p ".tau_ledger/freed"
have_logB="$(ls -1t analysis/freed/logB_receipt_*.json 2>/dev/null | head -n1 || true)"
have_relidx="$(ls -1t analysis/freed/relative_index_*.json 2>/dev/null | head -n1 || true)"
status="pending"; note="awaiting inputs for real factorization checks (B decomposition, Σ sectors, monodromy ties)"
[ -n "$have_logB" ] && [ -n "$have_relidx" ] && status="ok" && note="minimal gate satisfied: have logB + relative_index"
printf "{\\n"                                   >  "$out"
printf "  \\"angle\\": \\"06_factorization_gate\\",\\n"   >> "$out"
printf "  \\"timestamp\\": \\"%s\\",\\n" "$ts"            >> "$out"
printf "  \\"status\\": \\"%s\\",\\n" "$status"           >> "$out"
printf "  \\"have_logB\\": \\"%s\\",\\n" "$have_logB"     >> "$out"
printf "  \\"have_relative_index\\": \\"%s\\",\\n" "$have_relidx" >> "$out"
printf "  \\"note\\": \\"%s\\"\\n" "$note"                >> "$out"
printf "}\\n"                                             >> "$out"
echo "$out"
