#!/usr/bin/env bash
set +H
umask 022
OUT="docs/monographs/ramanujan_face_run1.tex"
: > "$OUT"
printf "%% Auto-generated by make_raman_face_run1_tex.sh\\n" >> "$OUT"
printf "\\\\documentclass[11pt]{article}\\n" >> "$OUT"
printf "\\\\usepackage{amsmath,amssymb,geometry,longtable}\\n" >> "$OUT"
printf "\\\\geometry{margin=1in}\\n" >> "$OUT"
printf "\\\\title{Ramanujan-Signed Modular Witnesses from Facial Landmarks: Run 1}\\n" >> "$OUT"
printf "\\\\date{\\\\today}\\n" >> "$OUT"
printf "\\\\begin{document}\\n\\\\maketitle\\n" >> "$OUT"
printf "We record a preregistered batch of 50 three-dimensional facial landmark sets and bind them to modular arithmetic witnesses via a signed receipt chain. Let \\\\Delta(q)=q\\prod_{n\\ge 1}(1-q^n)^{24}=\\sum_{n\\ge 1}\\tau(n)q^n. Faces are interpreted as morphic embeddings admitted to a modular basin; receipts carry SHA-256 anchors and optional OP\\_RETURN pointers.\\\\\\n" >> "$OUT"
printf "\\\\section*{Receipts and Chain Anchor}\\nWe include the manifest (JSON) for reproducibility; the corridor receipt records \\\\texttt{op\\_return\\_hex}, \\\\texttt{txid}, and \\\\texttt{block} when available.\\\\\\n" >> "$OUT"
printf "\\\\section*{Face Table}\\nThe following longtable enumerates faces by identifier and digest.\\\\\\n" >> "$OUT"
printf "\\\\begin{longtable}{p{0.28\\\\textwidth}p{0.62\\\\textwidth}}\\\\hline\\\\textbf{Face ID} & \\\\textbf{SHA-256 Digest}\\\\\\\\\\\\hline\\\\endfirsthead\\\\hline\\\\textbf{Face ID} & \\\\textbf{SHA-256 Digest}\\\\\\\\\\\\hline\\\\endhead" >> "$OUT"
if [ -f analysis/validation/SIGNED_DATASET.receipt.tsv ]; then
  awk "NR>1" analysis/validation/SIGNED_DATASET.receipt.tsv | while IFS=$'\t' read -r A B C D E; do printf "%s & %s \\\\\\\\\\\\ \\n" "$A" "$B"; done >> "$OUT"
fi
printf "\\\\hline\\\\end{longtable}\\n" >> "$OUT"
printf "\\\\section*{Modular Tie-in}\\nWe track available coefficients \\\\tau(p) where present in receipts; missing entries remain notated as NA, pending certified extraction.\\\\\\n" >> "$OUT"
printf "\\\\end{document}\\n" >> "$OUT"
