name: companion-guard
on:
  push: { branches: [ main ] }
  pull_request:
  workflow_dispatch: {}
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify canonical companions
        run: scripts/geom/guard_companions.sh
