name: holonomy-align
on:
  push:
  workflow_dispatch:
jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash scripts/ops/holonomy_demo.sh
      - uses: actions/upload-artifact@v4
        with:
          name: holonomy-receipt-${{ github.run_id }}
          path: .cache/holonomy_example.json
