name: automorphic-catalog
on:
  push:
    branches: ["**"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build catalog
        run: python scripts/automorphic/_catalog.py
      - name: Commit updated catalog
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add docs/automorphic/catalog.md || true
          git commit -m "automorphic: refresh catalog [skip ci]" || true
          git push || true
