name: tau-phys-guards
on:
  push: {branches: ["**"]}
  pull_request: {}
jobs:
  guards:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Ensure bash settings
        run: echo "set +H" >> "$HOME/.bashrc"
      - name: Run lattice + gap + cap + recursion guards
        shell: bash
        run: |
          set -Eeuo pipefail; set +H; umask 022
          bash scripts/phys/lattice_from_params.sh .tau_ledger/phys/lattice.json
          EPS=1e-6 bash scripts/phys/spectral_gap_guard.sh .tau_ledger/phys/lattice.json
          bash scripts/phys/debye_cap_from_lattice.sh .tau_ledger/phys/lattice.json .tau_ledger/phys/debye_cap.txt
          bash scripts/lean/recursion_cap_guard.sh .tau_ledger/phys/debye_cap.txt src || true
