name: release-staple
on:
  release:
    types: [published]
jobs:
  staple:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run assure
        run: |
          bash -lc "scripts/assure.sh"
      - name: Attach receipts to release
        uses: softprops/action-gh-release@v2
        with:
          files: receipts/*.txt
