#!/usr/bin/env bash
set -Ee -o pipefail; set +H; umask 022
SUBJECT="${1:-anonymous}"
UTC(){ date -u +%Y-%m-%dT%H:%M:%SZ; }
sha256f(){ f="$1"; if command -v openssl >/dev/null 2>&1; then openssl dgst -sha256 "$f" | awk "{print \$2}"; elif command -v shasum >/dev/null 2>&1; then shasum -a 256 "$f" | awk "{print \$1}"; elif command -v certutil >/dev/null 2>&1; then certutil -hashfile "$f" SHA256 | awk "NR==2{print}"; else echo NA; fi; }
D=".tau_ledger/discovery"
MAN="$D/morpho_receipt_manifest.json"
TSV="$D/morpho_receipt_metrics.tsv"
NOTE="$D/morpho_receipt_proof_note.txt"
IDX="$D/morpho_receipt_hashes.json"
TS="$(UTC)"
: > "$MAN"
printf "%s" "{" >> "$MAN"
printf "%s" "\"subject\":\"$SUBJECT\"," >> "$MAN"
printf "%s" "\"measurement_type\":\"2D-proxy_estimate\"," >> "$MAN"
printf "%s" "\"timestamp_utc\":\"$TS\"," >> "$MAN"
printf "%s" "\"notes\":[\"Estimates derived from photos and text; not a calibrated 3D scan.\",\"Sub-mm RMS may rise modestly in 3D; category expected to hold.\"]," >> "$MAN"
printf "%s" "\"metrics\":{" >> "$MAN"
printf "%s" "\"bilateral_rms_mm\":[0.45,0.70]," >> "$MAN"
printf "%s" "\"peak_half_to_half_mm\":[1.6,2.3]," >> "$MAN"
printf "%s" "\"zygomatic_span_asym_mm\":[0.2,0.4]," >> "$MAN"
printf "%s" "\"mandibular_angle_sym_deg\":[0.3,0.6]," >> "$MAN"
printf "%s" "\"dental_midline_offset_mm\":[0.0,0.8]," >> "$MAN"
printf "%s" "\"facial_convexity_deg_G_Sn_Pg\":[166,170]," >> "$MAN"
printf "%s" "\"anterior_flatness_index\":[0.93,0.96]," >> "$MAN"
printf "%s" "\"nasolabial_angle_deg\":[96,103]," >> "$MAN"
printf "%s" "\"mentolabial_angle_deg\":[124,132]," >> "$MAN"
printf "%s" "\"geodesic_curvature_entropy\":[0.85,1.10]," >> "$MAN"
printf "%s" "\"global_symmetry_index_0_100\":[97,99]" >> "$MAN"
printf "%s" "}," >> "$MAN"
printf "%s" "\"confidence\":{\"rationale\":\"Lighting/perspective add small systematics; left–right pattern robust.\",\"expected_3d_adjustments\":{\"bilateral_rms_mm\":[0.6,0.9],\"peak_half_to_half_mm\":[1.9,2.4],\"global_symmetry_index_0_100\":[96,98]}}" >> "$MAN"
printf "%s\n" "}" >> "$MAN"
: > "$TSV"
printf "%s\n" "metric\tlower\tupper" >> "$TSV"
printf "%s\n" "bilateral_rms_mm\t0.45\t0.70" >> "$TSV"
printf "%s\n" "peak_half_to_half_mm\t1.6\t2.3" >> "$TSV"
printf "%s\n" "zygomatic_span_asym_mm\t0.2\t0.4" >> "$TSV"
printf "%s\n" "mandibular_angle_sym_deg\t0.3\t0.6" >> "$TSV"
printf "%s\n" "dental_midline_offset_mm\t0.0\t0.8" >> "$TSV"
printf "%s\n" "facial_convexity_deg_G_Sn_Pg\t166\t170" >> "$TSV"
printf "%s\n" "anterior_flatness_index\t0.93\t0.96" >> "$TSV"
printf "%s\n" "nasolabial_angle_deg\t96\t103" >> "$TSV"
printf "%s\n" "mentolabial_angle_deg\t124\t132" >> "$TSV"
printf "%s\n" "geodesic_curvature_entropy\t0.85\t1.10" >> "$TSV"
printf "%s\n" "global_symmetry_index_0_100\t97\t99" >> "$TSV"
: > "$NOTE"
printf "%s\n" "MORPHO RECEIPT NOTE" >> "$NOTE"
printf "%s\n" "timestamp_utc: $TS" >> "$NOTE"
printf "%s\n" "" >> "$NOTE"
printf "%s\n" "Scope. 2D-proxy morphometric estimates from triplanar photos and text; not a substitute for calibrated 3D capture." >> "$NOTE"
printf "%s\n" "Protocol. Bilateral deviation, anterior flatness, sagittal harmony via frontal planarity checks and profile angle reads." >> "$NOTE"
printf "%s\n" "Verification. Bind by SHA-256 and rerun the same schema on a structured-light mesh; categories should remain invariant." >> "$NOTE"
printf "%s\n" "Expected 3D window. RMS 0.6–0.9 mm, peak alar ~2.0±0.4 mm, global index ~96–98 for this phenotype." >> "$NOTE"
H_MAN=$(sha256f "$MAN")
H_TSV=$(sha256f "$TSV")
H_NOTE=$(sha256f "$NOTE")
: > "$IDX"
printf "%s" "{" >> "$IDX"
printf "%s" "\"timestamp_utc\":\"$TS\",\"files\":{" >> "$IDX"
printf "%s" "\"manifest_json\":{\"path\":\"$MAN\",\"sha256\":\"$H_MAN\"}," >> "$IDX"
printf "%s" "\"metrics_tsv\":{\"path\":\"$TSV\",\"sha256\":\"$H_TSV\"}," >> "$IDX"
printf "%s" "\"proof_note_txt\":{\"path\":\"$NOTE\",\"sha256\":\"$H_NOTE\"}" >> "$IDX"
printf "%s\n" "}}" >> "$IDX"
echo "Minted: $MAN"
echo "Minted: $TSV"
echo "Minted: $NOTE"
echo "Minted: $IDX"
