#!/usr/bin/env bash
. "$(dirname "$0")/../safe/_env.sh"
set -e
cd "$HOME/Desktop/tau_crystal/tau_crystal" || exit 1
T="$1"; [ -n "$T" ] || { echo "usage: duplicate_target_suite.sh <TARGET_ID>" >&2; exit 2; }
./scripts/safe/writefile.sh "scripts/meta/${T}_sign_infty.sh" "#!/usr/bin/env bash"
printf "%s\n" ". \"$(dirname "$0")/../safe/_env.sh\"" >> "scripts/meta/${T}_sign_infty.sh"
printf "%s\n" "set -e" >> "scripts/meta/${T}_sign_infty.sh"
printf "%s\n" "cd \"$HOME/Desktop/tau_crystal/tau_crystal\" || exit 1" >> "scripts/meta/${T}_sign_infty.sh"
printf "%s\n" "python scripts/safe/sign_at_infinity.py receipts/${T}_receipt.json receipts/${T}_discriminant.json" >> "scripts/meta/${T}_sign_infty.sh"
chmod +x "scripts/meta/${T}_sign_infty.sh"
./scripts/safe/writefile.sh "scripts/meta/${T}_root_number.sh" "#!/usr/bin/env bash"
printf "%s\n" ". \"$(dirname "$0")/../safe/_env.sh\"" >> "scripts/meta/${T}_root_number.sh"
printf "%s\n" "set -e" >> "scripts/meta/${T}_root_number.sh"
printf "%s\n" "cd \"$HOME/Desktop/tau_crystal/tau_crystal\" || exit 1" >> "scripts/meta/${T}_root_number.sh"
printf "%s\n" "python scripts/safe/root_number.py receipts/${T}_receipt.json data/${T}_local_signs.csv receipts/${T}_root_number.json" >> "scripts/meta/${T}_root_number.sh"
chmod +x "scripts/meta/${T}_root_number.sh"
./scripts/safe/writefile.sh "scripts/meta/${T}_verify.sh" "#!/usr/bin/env bash"
printf "%s\n" ". \"$(dirname "$0")/../safe/_env.sh\"" >> "scripts/meta/${T}_verify.sh"
printf "%s\n" "set -e" >> "scripts/meta/${T}_verify.sh"
printf "%s\n" "cd \"$HOME/Desktop/tau_crystal/tau_crystal\" || exit 1" >> "scripts/meta/${T}_verify.sh"
printf "%s\n" "JR=receipts/${T}_receipt.json; JG=receipts/genus/${T}_observation.json" >> "scripts/meta/${T}_verify.sh"
printf "%s\n" "[ -s \"$JR\" ] && [ -s \"$JG\" ] || { echo missing receipts >&2; exit 2; }" >> "scripts/meta/${T}_verify.sh"
printf "%s\n" "pyr(){ python scripts/safe/json_read.py \"\$1\" \"\$JR\"; }" >> "scripts/meta/${T}_verify.sh"
printf "%s\n" "pyg(){ python scripts/safe/json_read.py \"\$1\" \"\$JG\"; }" >> "scripts/meta/${T}_verify.sh"
printf "%s\n" "gr_a=\$(pyr fibration.generic_mordell_weil_rank); sr_a=\$(pyr fibration.special_fiber_rank); gr_g=\$(pyg generic.zero_modes); sr_g=\$(pyg twisted.zero_modes)" >> "scripts/meta/${T}_verify.sh"
printf "%s\n" "[ \"\$gr_a\" = \"\$gr_g\" ] && [ \"\$sr_a\" = \"\$sr_g\" ] && { echo PASS; exit 0; } || { echo FAIL \"arith:(\$gr_a,\$sr_a) genus:(\$gr_g,\$sr_g)\"; exit 1; }" >> "scripts/meta/${T}_verify.sh"
chmod +x "scripts/meta/${T}_verify.sh"
./scripts/safe/writefile.sh "scripts/meta/${T}_status.sh" "#!/usr/bin/env bash"
printf "%s\n" ". \"$(dirname "$0")/../safe/_env.sh\"" >> "scripts/meta/${T}_status.sh"
printf "%s\n" "set -e" >> "scripts/meta/${T}_status.sh"
printf "%s\n" "cd \"$HOME/Desktop/tau_crystal/tau_crystal\" || exit 1" >> "scripts/meta/${T}_status.sh"
printf "%s\n" "JR=receipts/${T}_receipt.json; JG=receipts/genus/${T}_observation.json" >> "scripts/meta/${T}_status.sh"
printf "%s\n" "pyr(){ python scripts/safe/json_read.py \"\$1\" \"\$JR\"; }; pyg(){ python scripts/safe/json_read.py \"\$1\" \"\$JG\"; }" >> "scripts/meta/${T}_status.sh"
printf "%s\n" "echo \"— ${T} STATUS —\"; echo \"a4:   \$(pyr curve.a4)\"; echo \"a6:   \$(pyr curve.a6)\"; echo \"disc: \$(pyr curve.discriminant_sign)\"; echo \"w:    \$(pyr curve.root_number)\"; echo \"genus: \$(pyg generic.zero_modes) → \$(pyg twisted.zero_modes)\"; echo \"fib:   \$(pyr fibration.generic_mordell_weil_rank) → \$(pyr fibration.special_fiber_rank)\"; echo \"regdet:\$(pyr curve.regulator_det) size:\$(pyr height_matrix_size)\"" >> "scripts/meta/${T}_status.sh"
chmod +x "scripts/meta/${T}_status.sh"
./scripts/safe/writefile.sh "scripts/meta/${T}_height_reduce.sh" "#!/usr/bin/env bash"
printf "%s\n" ". \"$(dirname "$0")/../safe/_env.sh\"" >> "scripts/meta/${T}_height_reduce.sh"
printf "%s\n" "set -e" >> "scripts/meta/${T}_height_reduce.sh"
printf "%s\n" "cd \"$HOME/Desktop/tau_crystal/tau_crystal\" || exit 1" >> "scripts/meta/${T}_height_reduce.sh"
printf "%s\n" "python scripts/safe/height_det.py receipts/${T}_receipt.json data/${T}_height_matrix.csv receipts/${T}_regulator.json" >> "scripts/meta/${T}_height_reduce.sh"
printf "%s\n" "./scripts/meta/${T}_verify.sh || true" >> "scripts/meta/${T}_height_reduce.sh"
chmod +x "scripts/meta/${T}_height_reduce.sh"
./scripts/safe/writefile.sh "scripts/meta/${T}_height_full.sh" "#!/usr/bin/env bash"
printf "%s\n" ". \"$(dirname "$0")/../safe/_env.sh\"" >> "scripts/meta/${T}_height_full.sh"
printf "%s\n" "set -e" >> "scripts/meta/${T}_height_full.sh"
printf "%s\n" "cd \"$HOME/Desktop/tau_crystal/tau_crystal\" || exit 1" >> "scripts/meta/${T}_height_full.sh"
printf "%s\n" "python scripts/safe/height_full_det.py receipts/${T}_receipt.json data/${T}_height_full.csv receipts/${T}_regulator_full.json" >> "scripts/meta/${T}_height_full.sh"
printf "%s\n" "./scripts/meta/${T}_verify.sh || true" >> "scripts/meta/${T}_height_full.sh"
chmod +x "scripts/meta/${T}_height_full.sh"
echo "$T"
