name: monograph-assurance
on: [push, pull_request]

jobs:
  assure:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install elan (Lean toolchain, non-interactive)
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          Invoke-WebRequest -Uri https://raw.githubusercontent.com/leanprover/elan/master/elan-init.ps1 -OutFile elan-init.ps1
          .\elan-init.ps1 -NoPrompt -DefaultToolchain "leanprover/lean4:stable"
          "$env:USERPROFILE\.elan\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Run assurance (bash harness)
        shell: bash
        run: |
          set -euo pipefail
          dos2unix assure.sh 2>/dev/null || true
          ./assure.sh
