name: assure

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Emit Tau Crystal Receipt for Guardian
        shell: bash
        run: |
          set -euo pipefail
          cat > tau-crystal-receipt.json <<JSON
          {
            "kind": "tau-crystal-receipt",
            "version": "1",
            "repo": "${{ github.repository }}",
            "sha":  "${{ github.sha }}",
            "run_id": "${{ github.run_id }}",
            "event": "${{ github.event_name }}",
            "runner": "assure.yml:build"
          }
          JSON
          cp tau-crystal-receipt.json manifest.json
          command -v jq >/dev/null || sudo apt-get update && sudo apt-get install -y jq
          jq -e ".kind==\"tau-crystal-receipt\"" tau-crystal-receipt.json >/dev/null
          jq -e ".kind==\"tau-crystal-receipt\"" manifest.json >/dev/null

      - name: Upload artifact for Guardian (exact name)
        uses: actions/upload-artifact@v4
        with:
          name: tau-crystal-manifest
          path: |
            tau-crystal-receipt.json
            manifest.json
          if-no-files-found: error

      - name: Create manifest (Linux)
        run: |
          mkdir -p out
          ts=$(date -u +%FT%TZ)
          cat > out/manifest.json <<'EOF'
          {
            "kind": "tau-crystal-receipt",
            "version": 1,
            "timestamp": "__TS__",
            "run_id": "${{ github.run_id }}",
            "sha": "${{ github.sha }}",
            "repo": "${{ github.repository }}",
            "event": "${{ github.event_name }}",
            "os": "linux"
          }
          EOF
          sed -i "s/__TS__/$ts/" out/manifest.json

      - name: Show manifest
        run: cat out/manifest.json

      - name: Upload manifest
        uses: actions/upload-artifact@v4
        with:
          name: tau-crystal-manifest
          path: out/manifest.json
          if-no-files-found: error
          retention-days: 7

  guardian_artifact:
    name: Tau Crystal Guardian / Tau Crystal Receipt (artifact)
    runs-on: ubuntu-latest
    # If your main job has an id like "build", uncomment the next line so this runs after it:
    # needs: [build]
    steps:
      - uses: actions/checkout@v4

      - name: Emit Tau Crystal Receipt for Guardian
        shell: bash
        run: |
          set -euo pipefail
          cat > tau-crystal-receipt.json <<JSON
          {
            "kind": "tau-crystal-receipt",
            "version": "1",
            "repo": "${{ github.repository }}",
            "sha":  "${{ github.sha }}",
            "run_id": "${{ github.run_id }}",
            "event": "${{ github.event_name }}",
            "runner": "assure.yml"
          }
          JSON
          # Provide BOTH filenames—Guardian may look for manifest.json
          cp tau-crystal-receipt.json manifest.json
          jq -e '.kind=="tau-crystal-receipt"' tau-crystal-receipt.json >/dev/null
          jq -e '.kind=="tau-crystal-receipt"' manifest.json >/dev/null

      - name: Upload artifact for Guardian (exact name)
        uses: actions/upload-artifact@v4
        with:
          name: tau-crystal-manifest
          path: |
            tau-crystal-receipt.json
            manifest.json
          if-no-files-found: error
