name: assure
on:
  push: { branches: ["**"] }
  pull_request: {}
jobs:
  assure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
    steps:
      - uses: actions/checkout@v4
      - name: Run Ï„-Crystal assure
        run: |
          set -euo pipefail
          chmod +x scripts/assure.sh
          RECEIPT="$(scripts/assure.sh)"
          echo "RECEIPT=$RECEIPT" >> "$GITHUB_ENV"
          sed -n '1,4p' "$RECEIPT"
      - name: Upload receipt
        uses: actions/upload-artifact@v4
        with:
          name: tau-receipt
          path: ${{ env.RECEIPT }}
