name: monograph-assurance
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  assure:
    runs-on: ubuntu-latest
    env:
      TAUCRYSTAL_SIG_KEY: ${{ secrets.TAUCRYSTAL_SIG_KEY }}
    steps:
      - name: Stamp docs (deterministic if available)
        run: |
          if [ -f scripts/tauc.py ]; then
            python scripts/tauc.py stamp
          else
            echo "[info] no scripts/tauc.py; skipping stamp"
          fi
      - name: Run verification
      - name: Normalize manifest paths (Windows→POSIX)
        run: python scripts/normalize_manifest_paths.py
        run: python scripts/tau_verify.py
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.x' }

      - name: Show versions
        shell: bash
        run: |
          set -eux
          which lean
          lean --version
          lake --version

      - name: Run assurance harness
        shell: pwsh
        run: powershell -ExecutionPolicy Bypass -File .\assure.ps1

      - name: Upload signed manifests
        uses: actions/upload-artifact@v4
        with:
          name: manifests
          path: |
            manifest_assure1.json
            manifest_assure1.json.sha256
            manifest_assure1.json.hmac
            manifest_assure2.json
            manifest_assure2.json.sha256
            manifest_assure2.json.hmac
