# .github/workflows/assure.yml
name: assure

on:
  push:
  pull_request:

concurrency:
  group: assure-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-assure:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      # Cache elan toolchains to speed up installs
      - name: Cache elan toolchains
        uses: actions/cache@v4
        with:
          path: ~/.elan
          key: elan-${{ runner.os }}-${{ hashFiles('lean-toolchain') }}

      - name: Install elan (Lean toolchain) in bash
        run: |
          set -euxo pipefail
          curl -L https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -o elan-init.sh
          bash elan-init.sh -y
          echo "$HOME/.elan/bin" >> "$GITHUB_PATH"
          "$HOME/.elan/bin/elan" default "$(cat lean-toolchain)"
          "$HOME/.elan/bin/lean" --version
          "$HOME/.elan/bin/lake" --version || true

      # Cache Lake build outputs & deps
      - name: Cache Lake build & deps
        uses: actions/cache@v4
        with:
          path: |
            .lake
            lake-packages
          key: lake-${{ runner.os }}-${{ hashFiles('lean-toolchain') }}-${{ hashFiles('lakefile.lean') }}

      # Normalize line endings in case scripts were committed with CRLF
      - name: Normalize line endings for bash
        run: |
          set -euxo pipefail
          sed -i 's/\r$//' assure.sh || true
          sed -i 's/\r$//' tools/*.sh || true

      - name: Make scripts executable
        run: |
          set -euxo pipefail
          chmod +x assure.sh || true
          chmod +x tools/*.sh || true

      - name: Bash harness
        run: ./assure.sh

      - name: Linear-in-size probe
        run: ./tools/verify_linear.sh | tee linear_size.csv

      - name: Linear-in-reps probe
        run: ./tools/verify_linear_reps.sh | tee linear_reps.csv

      - name: Upload probe CSVs
        uses: actions/upload-artifact@v4
        with:
          name: linearity-probes
          path: |
            linear_size.csv
            linear_reps.csv
