name: assure

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create manifest
        run: |
          mkdir -p out
          cat > out/manifest.json <<JSON
          {
            "receipt_version": 1,
            "run_id": "${{ github.run_id }}",
            "sha": "${{ github.sha }}",
            "repo": "${{ github.repository }}",
            "event": "${{ github.event_name }}"
          }
          JSON

      - name: Show manifest
        run: cat out/manifest.json

      - name: Upload manifest
        uses: actions/upload-artifact@v4
        with:
          name: tau-crystal-manifest
          path: out/manifest.json
          if-no-files-found: error
          retention-days: 7
