name: assure
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install elan (Lean toolchain)
        run: |
          curl -sSfL https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh | sh -s -- -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
      - name: Show tool versions
        run: |
          lean --version
          lake --version
      - name: Build
        run: lake build
      - name: Emit receipt
        run: bash scripts/assure.sh
      - name: Upload manifest
        uses: actions/upload-artifact@v4
        with:
          name: tau-crystal-manifest
          path: |
            out/manifest.json
            out/fusion.stdout.txt
