# .github/workflows/assure.yml
name: assure

on:
  push:
  pull_request:

jobs:
  run-assure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install elan (Lean toolchain) in bash
        run: |
          curl -L https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -o elan-init.sh
          bash elan-init.sh -y
          echo "$HOME/.elan/bin" >> "$GITHUB_PATH"
          "$HOME/.elan/bin/elan" default "$(cat lean-toolchain)"
          "$HOME/.elan/bin/lean" --version
          "$HOME/.elan/bin/lake" --version || true

      - name: Make scripts executable
        run: |
          chmod +x assure.sh tools/*.sh || true

      - name: Bash harness
        run: ./assure.sh

      - name: Linear-in-size probe
        run: ./tools/verify_linear.sh | tee linear_size.csv

      - name: Linear-in-reps probe
        run: ./tools/verify_linear_reps.sh | tee linear_reps.csv

      - name: Upload probe CSVs
        uses: actions/upload-artifact@v4
        with:
          name: linearity-probes
          path: |
            linear_size.csv
            linear_reps.csv
