name: assure

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create manifest (Linux)
        run: |
          mkdir -p out
          ts=$(date -u +%FT%TZ)
          cat > out/manifest.json <<'EOF'
          {
            "kind": "tau-crystal-receipt",
            "version": 1,
            "timestamp": "__TS__",
            "run_id": "${{ github.run_id }}",
            "sha": "${{ github.sha }}",
            "repo": "${{ github.repository }}",
            "event": "${{ github.event_name }}",
            "os": "linux"
          }
          EOF
          sed -i "s/__TS__/$ts/" out/manifest.json

      - name: Show manifest
        run: cat out/manifest.json

      - name: Upload manifest
        uses: actions/upload-artifact@v4
        with:
          name: tau-crystal-manifest
          path: out/manifest.json
          if-no-files-found: error
          retention-days: 7
