# .github/workflows/assure.yml
name: assure

on:
  push:
  pull_request:

concurrency:
  group: assure-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-assure:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Show repo tree (debug)
        run: |
          pwd
          ls -la
          echo
          ls -la tools || true

      - name: Cache elan toolchains
        uses: actions/cache@v4
        with:
          path: ~/.elan
          key: elan-${{ runner.os }}-${{ hashFiles('lean-toolchain') }}

      - name: Install elan (Lean toolchain)
        run: |
          set -euxo pipefail
          curl -L https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -o elan-init.sh
          bash elan-init.sh -y
          echo "$HOME/.elan/bin" >> "$GITHUB_PATH"
          "$HOME/.elan/bin/elan" default "$(cat lean-toolchain)"
          "$HOME/.elan/bin/lean" --version
          "$HOME/.elan/bin/lake" --version || true

      - name: Cache Lake build & deps
        uses: actions/cache@v4
        with:
          path: |
            .lake
            lake-packages
          key: lake-${{ runner.os }}-${{ hashFiles('lean-toolchain') }}-${{ hashFiles('lakefile.lean') }}

      - name: Normalize line endings for bash scripts
        run: |
          set -euxo pipefail
          sed -i 's/\r$//' assure.sh 2>/dev/null || true
          sed -i 's/\r$//' tools/*.sh 2>/dev/null || true

      - name: Make scripts executable (if present)
        run: |
          set -euxo pipefail
          chmod +x assure.sh        2>/dev/null || true
          chmod +x tools/*.sh       2>/dev/null || true

      - name: Assurance harness
        run: |
          set -euo pipefail
          if [[ -x ./assure.sh ]]; then
            ./assure.sh
          else
            echo "assure.sh not found; skipping harness (CI will still proceed)."
          fi

      - name: Linear-in-size probe (conditional)
        run: |
          set -euo pipefail
          if [[ -x ./tools/verify_linear.sh ]]; then
            ./tools/verify_linear.sh | tee linear_size.csv
          else
            echo "size,nnz,time_ms" > linear_size.csv
            echo "tools/verify_linear.sh not found; wrote header-only CSV."
          fi

      - name: Linear-in-reps probe (conditional)
        run: |
          set -euo pipefail
          if [[ -x ./tools/verify_linear_reps.sh ]]; then
            ./tools/verify_linear_reps.sh | tee linear_reps.csv
          else
            echo "reps,time_ms,per_rep_ms" > linear_reps.csv
            echo "tools/verify_linear_reps.sh not found; wrote header-only CSV."
          fi

      - name: Upload probe CSVs
        uses: actions/upload-artifact@v4
        with:
          name: linearity-probes
          path: |
            linear_size.csv
            linear_reps.csv
