name: assure
on:
  push:
  pull_request:
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run assure
        run: |
          bash -lc "scripts/assure.sh"
      - name: Attest receipt (soft fail if tool absent)
        run: |
          if [ -f tools/receipt2attestation.py ]; then python3 tools/receipt2attestation.py; else echo "no attestation tool; skipping"; fi
      - name: Upload receipts
        uses: actions/upload-artifact@v4
        with:
          name: receipts
          path: receipts/*.txt
