name: monograph-assurance
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  assure:
    runs-on: windows-latest
    env:
      TAUCRYSTAL_SIG_KEY: ${{ secrets.TAUCRYSTAL_SIG_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Lean (elan) non-interactive
        shell: bash
        run: |
          set -euxo pipefail
          curl -L https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -o elan-init.sh
          bash elan-init.sh -y --default-toolchain leanprover/lean4:v4.22.0
          echo "$HOME/.elan/bin" >> "$GITHUB_PATH"

      - name: Show versions
        shell: bash
        run: |
          set -eux
          which lean
          lean --version
          lake --version

      - name: Cache Lake build
        uses: actions/cache@v4
        with:
          path: |
            .lake/build
            .lake/packages
          key: ${{ runner.os }}-lake-${{ hashFiles('lakefile.lean', 'lakefile.toml') }}
          restore-keys: |
            ${{ runner.os }}-lake-

      - name: Run assurance harness
        shell: pwsh
        run: powershell -ExecutionPolicy Bypass -File .\assure.ps1

      - name: Upload signed manifests
        uses: actions/upload-artifact@v4
        with:
          name: manifests
          path: |
            manifest_assure1.json
            manifest_assure1.json.sha256
            manifest_assure1.json.hmac
            manifest_assure2.json
            manifest_assure2.json.sha256
            manifest_assure2.json.hmac
