name: assure
on: [push, pull_request]
jobs:
  strict:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: PANIC sentinel
        run: test ! -s PANIC || { echo "::error file=PANIC::panic asserted"; exit 2; }
      - name: Spec guard
        run: bash scripts/spec/spec_guard.sh
      - name: Runner attestation
        run: bash scripts/ops/attest_env.sh
      - name: Strict assurance (Bash)
        run: bash scripts/ops/assure_strict.sh
      - name: Offline verify (receipt-only)
        run: bash scripts/ops/verify_against_receipt.sh
      - name: Install elan
        run: |
          set -Eeuo pipefail
          curl -fsSL https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -o /tmp/elan.sh
          bash /tmp/elan.sh -y --default-toolchain stable
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
      - name: Lean verify-chain
        run: |
          set -Eeuo pipefail
          lake build verify-chain
          ./build/bin/verify-chain
      - name: Install cosign
        uses: sigstore/cosign-installer@v3
      - name: Sealed binary verifier
        run: bash scripts/ops/verify_release_binary.sh
