name: monograph-assurance
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  assure:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      # Install Lean (elan) NON-INTERACTIVE
      - name: Install Lean (elan)
        shell: bash
        run: |
          set -euxo pipefail
          curl -L https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -o elan-init.sh
          bash elan-init.sh -y --default-toolchain leanprover/lean4:v4.22.0
          echo "$HOME/.elan/bin" >> "$GITHUB_PATH"

      - name: Show versions
        shell: bash
        run: |
          set -eux
          which lean
          lean --version
          lake --version

      # Optional cache to speed builds
      - name: Cache Lake build
        uses: actions/cache@v4
        with:
          path: |
            .lake/build
            .lake/packages
          key: ${{ runner.os }}-lake-${{ hashFiles('lakefile.lean', 'lakefile.toml') }}
          restore-keys: |
            ${{ runner.os }}-lake-

      - name: Run assurance harness
        shell: pwsh
        run: powershell -ExecutionPolicy Bypass -File .\assure.ps1
