name: assure
on:
  push: { branches: ["**"] }
  pull_request: {}
jobs:
  assure:
    runs-on: ubuntu-latest
    steps:
      - name: Install tools (jq)
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y jq
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Run Ï„-Crystal assure
        run: |
          set -euxo pipefail
          chmod +x scripts/assure.sh
          RECEIPT="$(bash scripts/assure.sh || true)"
          echo "assure.sh returned path: [$RECEIPT]"
          test -n "$RECEIPT" && test -f "$RECEIPT" || { echo "::warning::assure produced no receipt"; touch assure-empty.txt; RECEIPT=assure-empty.txt; }
          echo "RECEIPT=$RECEIPT" >> "$GITHUB_ENV"
          sed -n '1,4p' "$RECEIPT"
      - name: Upload receipt
        uses: actions/upload-artifact@v4
        with:
          name: tau-receipt
          path: ${{ env.RECEIPT }}
