name: assure
on:
  pull_request:
  push:
jobs:
  strict:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Runner attestation
        run: bash scripts/ops/attest_env.sh
      - name: Spec guard
        run: bash scripts/spec/spec_guard.sh
      - name: Strict assurance
        run: bash scripts/ops/assure_strict.sh
      - name: Offline verify
        run: bash scripts/ops/verify_offline.sh
      - name: Upload attestations
        uses: actions/upload-artifact@v4
        with:
          name: tau-attest
          path: .tau_ledger/attest/*.json
