name: Gate main on verification

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 2 }
      - uses: actions/setup-python@v5
        with: { python-version: '3.x' }
      - name: Stamp & verify
        run: |
          python scripts/tauc.py stamp
          PROOF_OF_WORK_BITS=8 python scripts/tauc.py verify
      - name: Emit verification transcript
        run: python scripts/log_transcript.py
      - name: Commit verification transcript
        run: |
          git config user.name "ci"
          git config user.email "ci@users.noreply.github.com"
          git add docs/ledger/last-good-run.json
          git diff --cached --quiet || git commit -m "ledger: record verified run $(date -u +%Y%m%d-%H%M%S)"
          git push
