name: CI Bench
on:
  workflow_dispatch:
  schedule:
    - cron: "17 6 * * 1"
jobs:
  bench:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        mode: [cold, warm]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Lean
        uses: leanprover/lean-action@v1
        with:
          version: "stable"
      - name: Cache Lake (warm only)
        if: matrix.mode == warm
        uses: actions/cache@v4
        with:
          path: |
            ~/.elan
            .lake
            lake-packages
          key: ${{ runner.os }}-lake-${{ hashFiles(
            'lake-manifest.json'
          ) }}
      - name: Bench
        shell: bash
        run: |
          set -Eeuo pipefail; set +H
          if [ "${{ matrix.mode }}" = "cold" ]; then rm -rf .lake lake-packages build 2>/dev/null || true; fi
          START=$(date -u +%s)
          if make -q tau 2>/dev/null; then make tau; else make tau || lake build; fi
          ./scripts/assure.sh
          END=$(date -u +%s); DUR=$((END-START))
          REC=$(tail -n1 receipts/CHAIN | awk '{print $2}')
          SHA=$(sha256sum "$REC" | awk '{print $1}')
          TS=$(date -u +%Y-%m-%dT%H:%M:%SZ); COMMIT=$(git rev-parse --short=12 HEAD)
          MLREV=$(scripts/bench/mathlib_rev.sh || echo unknown)
          mkdir -p .tau_ledger/bench
          echo "{\"utc_iso\":\"$TS\",\"commit\":\"$COMMIT\",\"mode\":\"${{ matrix.mode }}\",\"os\":\"${{ runner.os }}\",\"runner\":\"github-actions\",\"mathlib_rev\":\"$MLREV\",\"duration_s\":$DUR,\"receipt_path\":\"$REC\",\"receipt_sha256\":\"$SHA\"}" >> .tau_ledger/bench/ci_runs.ndjson
      - name: Upload bench artifact
        uses: actions/upload-artifact@v4
        with:
          name: bench-${{ matrix.os }}-${{ matrix.mode }}
          path: .tau_ledger/bench/ci_runs.ndjson
