name: HEO Research — Spectral Matrix

on:
  push:
    branches: [ "main", "ci-**", "feat/**", "fix/**" ]
  pull_request:

jobs:
  spectral-matrix:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run spectral diagnostic
        run: |
          python ci/heo/research/spectral_matrix.py --sequence ci/data/sequences/periodic_7_0010010.json --k-min -6 --k-max 6 --xi 2.0 --top 5
