name: HEO Research Modules (optional)

on:
  push:
    branches: [ "main", "ci-**", "feat/**", "fix/**" ]
  pull_request:

jobs:
  adelic-product:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run adelic product check (S(n)=n, d=2, k=1)
        run: |
          python ci/heo/research/adelic_product_formula.py --coeffs 0 1 --k 1 --d 2 --primes 2 3 5 --N-max 4
