name: HEO Core CI

on:
  push:
    branches: [ "main", "ci-**", "feat/**", "fix/**" ]
  pull_request:

jobs:
  heo-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema

      - name: Validate receipts
        run: |
          python - <<'PY'
import json,sys,glob
from jsonschema import validate
schema=json.load(open("ci/heo/schemas/receipt.schema.json"))
ok=True
for f in glob.glob("receipts/heo/**/**/*.json", recursive=True):
    try:
        obj=json.load(open(f))
        validate(obj, schema)
        print("OK", f)
    except Exception as e:
        ok=False
        print("INVALID", f, e)
sys.exit(0 if ok else 1)
PY

      - name: Run required tests (Tier 0–5)
        run: |
          chmod +x ci/heo/scripts/*.py
          python ci/heo/scripts/compute_density.py --sequence ci/data/sequences/periodic_7_0010010.json --d 2 --k 0 --assert-bounds 0 1
          python ci/heo/scripts/finite_surgery_test.py
          python ci/heo/scripts/thinning_bound_test.py --sequence ci/data/sequences/periodic_7_0010010.json --thinning ci/data/sequences/thinning_maps.json
          python ci/heo/scripts/periodic_rationality_test.py --sequence ci/data/sequences/periodic_7_0010010.json
          python ci/heo/scripts/compute_pressure.py --sequence ci/data/sequences/periodic_7_0010010.json --beta 0.7

      - name: Run optional tests (Tiers 6–11, non-blocking)
        continue-on-error: true
        run: |
          python ci/heo/scripts/residue_density_test.py || true
          python ci/heo/scripts/p_adic_limsup_probe.py || true
          python ci/heo/scripts/brocard_fixture.py || true

      - name: Summarize receipts
        run: |
          python ci/heo/scripts/report_receipts.py
