name: HEO Research — ML Predictor

on:
  push:
    branches: [ "main", "ci-**", "feat/**", "fix/**" ]
  pull_request:

jobs:
  heo-ml:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install numpy
        run: |
          python -m pip install --upgrade pip
          pip install numpy
      - name: Train + evaluate linear predictor
        run: |
          python ci/heo/research/ml_predictor.py --train --eval --target_mae 0.02
