name: tau-crystal-ci
on: [push, pull_request]

jobs:
  win-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Stamp docs (deterministic if available)
        run: |
          if [ -f scripts/tauc.py ]; then
            python scripts/tauc.py stamp
          else
            echo "[info] no scripts/tauc.py; skipping stamp"
          fi
      - name: Run verification
      - name: Normalize manifest paths (Windows→POSIX)
        run: python scripts/normalize_manifest_paths.py
        run: python scripts/tau_verify.py
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.x' }

      # Install Git for Windows Bash path (already present) and elan/lean
      - name: Assure (Bash harness)
        shell: bash
        run: |
          set -euo pipefail
          ./assure.sh

      - name: Linear size probe (Bash)
        shell: bash
        run: |
          set -euo pipefail
          ./tools/verify_linear.sh | tee linear_size.csv

      - name: Linear reps probe (Bash)
        shell: bash
        run: |
          set -euo pipefail
          ./tools/verify_linear_reps.sh | tee linear_reps.csv

      - name: Upload probe CSVs
        uses: actions/upload-artifact@v4
        with:
          name: probes
          path: |
            linear_size.csv
            linear_reps.csv
