name: win-ci

on:
  push:
    branches: [ "main" ]   # don't run on feature branches

jobs:
  noop:
    runs-on: windows-latest
    steps:
      - name: Skip for screenshots
        run: echo "Windows CI disabled on non-main branches for now."
