name: tau-crystal-ci

on:
  push:
    branches: [ chore/ci-ping ]

jobs:
  win-ci:
    name: win-ci (allow failure)
    runs-on: windows-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Placeholder
        shell: pwsh
        run: echo "Windows CI placeholder; allowed to fail for now."
