name: ci-bench
on:
  workflow_dispatch: {}
  push:
    branches: ["**"]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
jobs:
  bench:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - name: Setup Lean
        run: scripts/ci/setup_lean.sh
      - name: Build
        run: lake build
