name: ci-fast
on:
  push:
    branches: [ "**" ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Compute cache key
        id: key
        shell: bash
        run: |
          set -Eeuo pipefail; set +H
          if [ -f lake-manifest.json ]; then k=$(sha256sum lake-manifest.json | cut -c1-12); else k=$(date +%s); fi
          echo "val=${{ runner.os }}-$k" >> "$GITHUB_OUTPUT"
      - uses: leanprover/lean-action@v1
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          key: ${{ steps.key.outputs.val }}
          path: |
            .lake
            lake-packages
            lean_packages
      - name: lake build (fast path)
        shell: bash
        run: |
          set -Eeuo pipefail; set +H
          lake build
      - name: Save cache
        if: always()
        uses: actions/cache/save@v4
        with:
          key: ${{ steps.key.outputs.val }}
          path: |
            .lake
            lake-packages
            lean_packages
