name: ci-heavy

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - '.github/workflows/spec_guard.yml'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - '.github/workflows/spec_guard.yml'

concurrency:
  group: heavy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [0,1,2,3,4,5,6,7]   # bump to 8-way parallel
    steps:
      - uses: actions/checkout@v4

      # ---------- CACHES ----------
      - name: Cache Python (pip)
        if: ${{ hashFiles('**/requirements.txt', '**/poetry.lock', '**/pyproject.toml') != '' }}
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pypoetry
          key: ${{ runner.os }}-py-${{ hashFiles('**/requirements.txt', '**/poetry.lock', '**/pyproject.toml') }}

      - name: Cache Node (npm/pnpm/yarn)
        if: ${{ hashFiles('**/package-lock.json', '**/pnpm-lock.yaml', '**/yarn.lock') != '' }}
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ~/.pnpm-store
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json', '**/pnpm-lock.yaml', '**/yarn.lock') }}

      - name: Cache Rust (cargo)
        if: ${{ hashFiles('**/Cargo.lock') != '' }}
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache Go (modules)
        if: ${{ hashFiles('**/go.sum') != '' }}
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
          key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.sum') }}

      - name: Cache Go build cache
        if: ${{ hashFiles('**/go.mod') != '' }}
        uses: actions/cache@v4
        with:
          path: |
            ~/go/build
            ~/.cache/go-build
          key: ${{ runner.os }}-gobuild-${{ hashFiles('**/*.go','**/go.mod','**/go.sum') }}

      # ---------- SHARD PREP ----------
      - name: Prepare test shard
        id: shard
        run: |
          bash scripts/ci/shard_list.sh ${{ matrix.shard }} 8
          echo "Files in shard ${{ matrix.shard }}:"
          [ -s "${{ steps.shard.outputs.filesfile }}" ] && nl -ba "${{ steps.shard.outputs.filesfile }}" || echo "(none)"

      # ---------- PYTHON ----------
      - name: Run pytest (sharded; xdist if present)
        if: ${{ steps.shard.outputs.count != '0' && hashFiles('**/pytest.ini', '**/pyproject.toml', '**/requirements.txt') != '' }}
        run: |
          set -Eeuo pipefail
          if python -c "import xdist" 2>/dev/null; then
            xargs -a "${{ steps.shard.outputs.filesfile }}" -r -n 1 python -m pytest -q -n auto --dist loadfile --maxfail=1
          else
            xargs -a "${{ steps.shard.outputs.filesfile }}" -r -n 50 python -m pytest -q --maxfail=1
          fi

      # ---------- GO ----------
      - name: Run Go tests
        if: ${{ hashFiles('**/go.mod') != '' }}
        run: |
          set -Eeuo pipefail
          go test ./... -count=1 -parallel=8

      # ---------- RUST (sccache + cargo-chef) ----------
      - name: Setup sccache
        if: ${{ hashFiles('**/Cargo.toml') != '' }}
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Enable sccache
        if: ${{ hashFiles('**/Cargo.toml') != '' }}
        run: |
          echo "RUSTC_WRAPPER=$(which sccache)" >> "$GITHUB_ENV"
          echo "SCCACHE_GHA_ENABLED=on" >> "$GITHUB_ENV"

      - name: Install cargo-chef
        if: ${{ hashFiles('**/Cargo.toml') != '' }}
        run: cargo install cargo-chef --locked

      - name: cargo-chef prepare (deps recipe)
        if: ${{ hashFiles('**/Cargo.toml') != '' }}
        run: cargo chef prepare --recipe-path recipe.json

      - name: Cache cargo-chef cook layers
        if: ${{ hashFiles('**/Cargo.toml') != '' }}
        uses: actions/cache@v4
        with:
          path: |
            target
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-chef-${{ hashFiles('recipe.json') }}

      - name: cargo-chef cook (compile deps)
        if: ${{ hashFiles('**/Cargo.toml') != '' }}
        run: cargo chef cook --recipe-path recipe.json --release

      - name: Run Rust tests
        if: ${{ hashFiles('**/Cargo.toml') != '' }}
        run: |
          set -Eeuo pipefail
          cargo test --all --locked --quiet

      # ---------- NODE ----------
      - name: Run Node tests
        if: ${{ hashFiles('**/package-lock.json') != '' }}
        run: |
          set -Eeuo pipefail
          npm ci --prefer-offline
          npm test --silent

      # ---------- DOCKER (GHA cache) ----------
      - name: Setup Docker Buildx
        if: ${{ hashFiles('**/Dockerfile') != '' }}
        uses: docker/setup-buildx-action@v3

      - name: Build with GHA cache
        if: ${{ hashFiles('**/Dockerfile') != '' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: tau-crystal/ci:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # ---------- NO-OP FALLBACK ----------
      - name: No matching test runner
        if: ${{ always() && steps.shard.outputs.count == '0' && hashFiles('**/pytest.ini', '**/pyproject.toml', '**/requirements.txt', '**/go.mod', '**/Cargo.toml', '**/package-lock.json') == '' }}
        run: echo "[info] No known test manifests found; nothing to run in this job."
