name: ci-prewarm
on:
  schedule:
    - cron: '17 7 * * *'
  workflow_dispatch: {}
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  warm:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Lean
        run: scripts/ci/setup_lean.sh
      - name: lake build (prewarm cache)
        run: lake build
