name: corridor-verify

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

jobs:
  corridor:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Show environment
        run: |
          bash --version
          uname -a
      - name: Corridor verify + digest
        shell: bash
        run: |
          set -euo pipefail; set +H; umask 022; export LC_ALL=C LANG=C
          [ -x scripts/runtime/corridor_verify.sh ] || chmod +x scripts/runtime/corridor_verify.sh 2>/dev/null || true
          [ -x scripts/runtime/corridor_digest.sh ] || chmod +x scripts/runtime/corridor_digest.sh 2>/dev/null || true
          bash scripts/runtime/corridor_verify.sh || true
          bash scripts/runtime/corridor_digest.sh || true
      - name: Upload corridor artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: corridor-ledger
          path: |
            .tau_ledger/corridor_status.json
            .tau_ledger/field/corridor.json
          if-no-files-found: warn
