name: cross-replay
on:
  schedule:
    - cron: "17 3 * * *"
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  replay:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone (no actions)
        shell: bash
        run: |
          set +e
          REPO="${GITHUB_REPOSITORY}"
          REF="${GITHUB_REF_NAME:-${GITHUB_REF##*/}}"
          rm -rf repo && mkdir repo && cd repo
          git init -q
          git -c http.extraheader="AUTHORIZATION: basic $(printf x-access-token:%s | base64 -w0 <<<"$GITHUB_TOKEN")" \\
            remote add origin "https://github.com/${REPO}.git"
          git fetch -q --depth 1 origin "$REF"
          git checkout -q FETCH_HEAD
      - name: Install Lean toolchain (pinned bootstrap)
        shell: bash
        working-directory: repo
        run: |
          scripts/ci_hardening/pin_elan.sh .ci/elan.commit .ci/elan.sha256 .ci/elan-init.sh
          bash .ci/elan-init.sh -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
      - name: Replay receipt
        shell: bash
        working-directory: repo
        run: |
          lake build
          if [ -x ./scripts/assure.sh ]; then ./scripts/assure.sh; else bash scripts/plan/write_roots.sh; fi
          test -s ".tau_ledger/CHAIN" && tail -n1 .tau_ledger/CHAIN
