name: Execution Geometry Guard
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Guard Execution Geometry
        run: bash scripts/ci/check_execution_geometry.sh
