name: freed receipts (matrix)
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:

jobs:
  verify:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10','3.11','3.12']
        mode: ['diag','mixed']
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .
      FREED_SIGMA_MODE: ${{ matrix.mode }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run verifier
        run: python scripts/freed/rg_leaf_checks.py
      - name: Upload receipts
        uses: actions/upload-artifact@v4
        with:
          name: freed-${{ matrix.mode }}-py${{ matrix.python-version }}
          path: |
            analysis/freed
            .tau_ledger/freed
