name: freed receipts (angles)
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:

jobs:
  angles:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11']
        mode: ['diag','mixed']
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .
      FREED_SIGMA_MODE: ${{ matrix.mode }}
      FREED_MU0: '0.9'
      FREED_B: '0.02'
      FREED_ELL: '12.0'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Relative functor (composition)
        run: python scripts/freed/rel_functor_receipt.py
      - name: Curvature (trace identity + holonomy)
        run: python scripts/freed/curvature_receipt.py
      - name: APS split (bulk + eta/2 + Z)
        run: python scripts/freed/aps_split_receipt.py
      - name: Defect fusion (generators)
        run: python scripts/freed/defect_fusion_receipt.py
      - name: Index as volume (stack quotient)
        run: python scripts/freed/index_volume_receipt.py
      - name: Upload receipts
        uses: actions/upload-artifact@v4
        with:
          name: freed-angles-${{ matrix.mode }}-py${{ matrix.python-version }}
          path: |
            analysis/freed
            .tau_ledger/freed
