name: instrument-guard
on:
  push: { branches: [ main ] }
  pull_request:
  workflow_dispatch: {}
    branches-ignore: [ ci-spine-clean-* ]
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check instrument framing and required files
        run: |
          test -f docs/instrumentation/INSTRUMENT.md
          test -f docs/instrumentation/PROTOCOL.md
          test -f schemas/rational_invariants.csv
          test -f analysis/arith/canonical_cr_indices.txt
          test -f analysis/arith/j_coeffs_Z.txt
          echo "Instrument scaffolding present."
