name: lean-remote-cache
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Synthesize receipt (always)
        run: |
          mkdir -p .tau_ledger
          TS=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          cat > .tau_ledger/receipt.json <<EOF
{"version":"rcpt-1","timestamp":"$TS","status":"synthetic","note":"receipt-only workflow"}
EOF
          echo "[ok] wrote .tau_ledger/receipt.json"
      - name: Upload receipt artifact
        uses: actions/upload-artifact@v4
        with:
          name: smartcache-receipt
          path: .tau_ledger/receipt.json
          if-no-files-found: error
