name: lean-remote-cache
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Synthesize receipt
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p .tau_ledger
          TS=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          printf '{"version":"rcpt-1","timestamp":"%s","status":"synthetic","note":"receipt-only workflow"}\n' "$TS" > .tau_ledger/receipt.json
          test -s .tau_ledger/receipt.json && ls -l .tau_ledger/receipt.json
      - name: Upload receipt
        uses: actions/upload-artifact@v4
        with:
          name: smartcache-receipt
          path: .tau_ledger/receipt.json
          if-no-files-found: error
