name: ledger-tau

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  run-ledger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install numpy
        run: python -m pip install --upgrade pip && pip install numpy

      - name: Run bash ledger
        run: bash -x scripts/run_ledger_from_bash.sh

      - name: Upload manifest
        uses: actions/upload-artifact@v4
        with:
          name: manifest
          path: manifest.json
