name: ledger-tau

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  run-ledger:
    runs-on: ubuntu-latest
    steps:
      - name: Stamp docs (deterministic if available)
        run: |
          if [ -f scripts/tauc.py ]; then
            python scripts/tauc.py stamp
          else
            echo "[info] no scripts/tauc.py; skipping stamp"
          fi
      - name: Run verification
      - name: Normalize manifest paths (Windows→POSIX)
        run: python scripts/normalize_manifest_paths.py
        run: python scripts/tau_verify.py
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: python -m pip install --upgrade pip && pip install numpy pynacl

      - name: Run bash ledger
        env:
          # OPTIONAL: set this secret in repo settings for real Ed25519 signatures
          ED25519_SK_B64: ${{ secrets.ED25519_SK_B64 }}
        run: bash -x scripts/run_ledger_from_bash.sh

      - name: Upload manifest
        uses: actions/upload-artifact@v4
        with:
          name: manifest
          path: manifest.json

      - name: Show summary
        run: |
          python - <<'PY'
          import json, pathlib
          m = json.loads(pathlib.Path("manifest.json").read_text())
          print("### Manifest SHA256")
          print(f"`{m['manifest_sha256']}`")
          print("### Pivot digest")
          print(f"`{m['rank']['pivot_digest_hex']}`")
          if "signature" in m:
            print("### Signature")
            print(f"{m['signature']['scheme']}")
          PY
