name: lint
on:
  push:
  pull_request:
jobs:
  actionlint:
    runs-on: ubuntu-22.04
    steps:
      - name: enforce heredoc-free scripts
        run: scripts/ci_hardening/check_no_heredocs.sh
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: actionlint
        run: |
          curl -sSfL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash | bash -s -- -b ./.bin
          ./.bin/actionlint -color never
