name: Deploy Pages
on:
  push:
    branches: [ main, master ]
    paths:
      - 'docs/**'
      - 'README.md'
      - 'manifests/*.json'
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Stamp MONOGRAPH with live counters
        run: |
          COUNT=$(ls -1 manifests/*.json 2>/dev/null | wc -l | tr -d ' ')
          LATEST=$(ls -1 manifests/*.json 2>/dev/null | tail -n 1)
          ROOT=—
          [ -n "$LATEST" ] && ROOT=$(sed -n 's/.*"merkle_root"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$LATEST" | head -n 1)
          # simple stamp in an HTML comment for traceability
          echo "<!-- manifests=$COUNT latest=$ROOT -->" >> docs/MONOGRAPH/index.html
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
