name: Physics Limits (Warn-Only)
defaults:
  run:
    shell: bash
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  physics:
    runs-on: ubuntu-latest
    env:
      IO_FRAC: "0"
      T_TOL: "0.25"
    env:
      IO_FRAC: "0"
      T_TOL: "0.5"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Run physics feasibility + certificate (warn-only)
        run: bash scripts/physics/run_with_energy.sh
      - name: Fit energy coefficient (warn-only)
        run: PYTHONIOENCODING=UTF-8 python3 scripts/physics/fit_energy.py || true
      - name: Fit c_energy (warn-only)
        run: python3 scripts/physics/fit_energy.py || true
      - name: Upload physics artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: physics
          path: .tau_ledger/physics/*.json
          if-no-files-found: ignore
