name: poison-canary
on:
  workflow_dispatch:
  push:
    branches: ["**"]
  pull_request:

permissions:
  contents: read

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Poison refresh (soft-pass)
        shell: bash
        run: |
          set -Eeuo pipefail
          if [ -x scripts/poison-refresh.sh ]; then
            bash scripts/poison-refresh.sh || { echo "::warning::poison refresh failed; soft-passing"; }
          else
            echo "::notice::scripts/poison-refresh.sh missing; skipping"
          fi
