name: receipt
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  make-receipt:
    runs-on: ubuntu-22.04
    steps:
      - name: enforce heredoc-free scripts
        run: scripts/ci_hardening/check_no_heredocs.sh
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Synthesize receipt
        run: |
          mkdir -p .tau_ledger
          echo "{\"status\":\"synthetic\",\"note\":\"receipt-only workflow\",\"ref\":\"${GITHUB_REF}\",\"sha\":\"${GITHUB_SHA}\"}" > .tau_ledger/receipt.json
      - name: Upload receipt artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: smartcache-receipt
          path: .tau_ledger/receipt.json
          if-no-files-found: error
