name: receipt
on:
  push:
    paths: ['manifests/**','scripts/**']
  pull_request:
    paths: ['manifests/**','scripts/**']
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
    steps:
      - uses: actions/checkout@v4
      - run: scripts/verify-all.sh
