name: release-staple
on:
  release:
    types: [published]
jobs:
  staple:
    runs-on: ubuntu-22.04
    steps:
      - name: enforce heredoc-free scripts
        run: scripts/ci_hardening/check_no_heredocs.sh
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Run assure
        run: |
          bash -lc "scripts/assure.sh"
      - name: Attach receipts to release
        uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836
        with:
          files: receipts/*.txt
