name: self-test
on:
  push:
  pull_request:
jobs:
    branches-ignore: [ ci-spine-clean-* ]
    branches-ignore: [ ci-spine-clean-* ]
  say-hi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Echo env
        run: |
          echo "hello from $GITHUB_WORKFLOW on $GITHUB_REF"
          uname -a
          git --version
