name: smart-ci
on:
  push:
  pull_request:
jobs:
  smart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install system deps
        run: |
          sudo apt-get update -y
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends python3 python3-pip jq curl ca-certificates git tar gzip
      - name: Install Lean toolchain (elan)
        run: |
          curl -sSf https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh | sh -s -- -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
      - id: leanver
        name: Capture Lean version
        run: echo "lean=$(lean --version | head -n1)" >> "$GITHUB_OUTPUT"
      - id: mathsha
        name: Capture Mathlib SHA
        run: |
          set -e
          sha=unknown
          if command -v jq >/dev/null 2>&1 && [ -f lake-manifest.json ]; then
            sha="$(jq -r '.packages[]|select(.name=="mathlib")|.rev // .git // "unknown"' lake-manifest.json)"
          elif [ -x scripts/mathlib-sha.py ]; then
            sha="$(scripts/mathlib-sha.py || echo unknown)"
          fi
          echo "sha=$sha" >> "$GITHUB_OUTPUT"
      - name: Restore Mathlib cache
        uses: actions/cache@v4
        with:
          path: |
            lake-packages
          key: ${{ runner.os }}-lean-${{ steps.leanver.outputs.lean }}-mathlib-${{ steps.mathsha.outputs.sha }}
          restore-keys: |
            ${{ runner.os }}-lean-${{ steps.leanver.outputs.lean }}-
      - name: lake update
        run: lake update
      - name: lake build
        run: lake build
      - name: Emit CI pattern
        run: scripts/ci_pattern.sh
      - name: Emit receipt
        run: |
          mkdir -p .tau_ledger
          PH="unknown"; [ -f .tau_ledger/pattern.sha256 ] && PH="$(cat .tau_ledger/pattern.sha256)"
          printf '{"status":"ok","run_id":"%s","pattern":"%s"}' "$GITHUB_RUN_ID" "$PH" > .tau_ledger/receipt.json
      - name: Upload receipt (always)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: smartcache-receipt
          path: .tau_ledger/receipt.json
          if-no-files-found: error
      - name: Upload pattern (always)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: smartcache-pattern
          path: .tau_ledger/pattern.json
          if-no-files-found: error
