name: smart-ci
on:
  push:
  pull_request:
permissions:
  contents: read
  packages: write
jobs:
  smart:
    runs-on: ubuntu-latest
    container: "ghcr.io/leanprover/lean:latest"
    steps:
      - uses: actions/checkout@v4
      - name: Install system deps
        run: apt-get update -y && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends python3 python3-pip jq curl ca-certificates openssl git tar gzip
      - name: Lean SmartCache (hydrate/publish)
        uses: ./.github/actions/lean-smart
        env:
          ED25519_SK_B64: ${{ secrets.ED25519_SK_B64 }}
        with:
          working-directory: .
          elan-toolchain: "ghcr.io/leanprover/lean:latest"
          ghcr-namespace: "ghcr.io/${{ github.repository_owner }}/mathlib-olean"
          publish-on-miss: "true"
      - name: Synthesize receipt (always)
        if: ${{ always() }}
        run: mkdir -p .tau_ledger && if [ -s .tau_ledger/receipt.json ]; then echo "receipt already present"; else echo "{ \"status\":\"synthetic\", \"note\":\"build failed earlier; synthetic receipt\" }" > .tau_ledger/receipt.json; fi
      - name: Upload receipt artifact (always)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: smartcache-receipt
          path: .tau_ledger/receipt.json
          if-no-files-found: error
