name: smart-ci
on:
  push:
  pull_request:
permissions:
  contents: read
  packages: write
  pull-requests: write
jobs:
  lean:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/leanprover-community/lean:leanprover-lean4-v4.22.0
    steps:
      - uses: actions/checkout@v4
      - name: Lean SmartCache
        uses: ./.github/actions/lean-smart
        with:
          publish-on-miss: ${{ github.event_name == 'push' }}
      - name: Comment SmartCache result (PRs only)
        if: ${{ github.event_name == 'pull_request' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr comment ${{ github.event.pull_request.number }} --body "$(cat .smartcache_summary_line.txt 2>/dev/null || echo SmartCache\ summary\ unavailable)" || true
