name: smart-ci
on:
  push:
    branches: [ "main", "master", "feature/**", "feat/**" ]
  pull_request:
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Smart Mathlib cache + build
        uses: ./.github/actions/lean-smart
        with:
          working-directory: .
          elan-toolchain: "leanprover/lean4:v4.22.0"
          ghcr-namespace: "ghcr.io/\${{ github.repository_owner }}/mathlib-olean"
          publish-on-miss: "\${{ github.event_name == push && github.repository_owner == github.actor && true || false }}"
      - name: Verify receipt (if present)
