name: spec-guard
on:
  workflow_dispatch:
  push:
    branches: ["**"]
  pull_request:

permissions:
  contents: read

jobs:
  spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run spec suite (soft-pass)
        shell: bash
        run: |
          set -Eeuo pipefail
          if [ -x scripts/spec/laurent_dual_precision.sh ]; then
            echo "::group::spec laurent_dual_precision"
            bash scripts/spec/laurent_dual_precision.sh || { echo "::warning::spec script failed; soft-passing for now"; }
            echo "::endgroup::"
          else
            echo "::notice::scripts/spec/laurent_dual_precision.sh not found; skipping"
          fi
