name: spec-guard
on:
  push:
  pull_request:
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build demo manifest+receipt
        run: bash scripts/make_demo_receipt.sh
      - name: Run spec guard
        run: bash scripts/spec_guard.sh
