name: tau-receipt
on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - chore/ci-ping

concurrency:
  group: receipt-${{ github.ref }}
  cancel-in-progress: true

jobs:
  receipt:
    name: Tau Crystal Receipt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Write receipt
        shell: bash
        run: |
          set -euo pipefail
          echo '{
            "kind": "tau-crystal-receipt",
            "version": "1",
            "repo": "'"${GITHUB_REPOSITORY}"'",
            "sha": "'"${GITHUB_SHA}"'",
            "run_id": "'"${GITHUB_RUN_ID}"'",
            "event": "'"${GITHUB_EVENT_NAME}"'",
            "runner": "tau-receipt.yml"
          }' > tau-crystal-receipt.json
          cat tau-crystal-receipt.json
      - name: Verify receipt
        run: jq -e '.kind=="tau-crystal-receipt"' tau-crystal-receipt.json >/dev/null
      - name: Upload artifact (expected name)
        uses: actions/upload-artifact@v4
        with:
          name: tau-crystal-manifest
          path: tau-crystal-receipt.json
          if-no-files-found: error
