name: tau-crystal
on:
  push:
  pull_request:

jobs:
  receipt:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
        with:
          fetch-depth: 0

      - name: Emit receipt
        run: ./scripts/emit-receipt.sh

      - name: Save digest
        run: |
          mkdir -p out
          sha256sum out/manifest.json > out/manifest.json.sha256
          cat out/manifest.json
          echo "---- sha256 ----"
          cat out/manifest.json.sha256

      - name: Secondary checker (Python)
        run: |
          python - <<'PY'
          import json, hashlib, sys, pathlib
          p = pathlib.Path("out/manifest.json")
          data = json.loads(p.read_text(encoding="utf-8"))
          ok = True
          def fail(msg): 
              print("❌", msg); sys.exit(1)

          # Basic shape
          if data.get("kind") != "tau-crystal-receipt": fail("kind mismatch")
          for k in ["version","component","commit_hash","timestamp_utc"]:
              if k not in data: fail(f"missing {k}")

          # Types
          ts = data.get("tau_series", [])
          rk = data.get("rank_kernel", [])
          if not isinstance(ts, list) or not all(isinstance(x,(int,float)) for x in ts):
              fail("tau_series not list of numbers")
          if not isinstance(rk, list) or not all(isinstance(x,int) for x in rk):
              fail("rank_kernel not list of ints")

          # Hash-chain recompute (must match emitter)
          H = "0"*64
          def upd(event: str):
              nonlocal H
              H = hashlib.sha256((H + event).encode()).hexdigest()
          for v in ts: upd(f"tau:{v}")
          for v in rk: upd(f"rk:{v}")
          got = data.get("clock",{}).get("hash_chain","")
          if H != got: fail("clock.hash_chain mismatch")

          print("✅ secondary checker: PASS")
          PY

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tau-crystal-manifest
          path: |
            out/manifest.json
            out/manifest.json.sha256
          if-no-files-found: error
