name: tau-guardian
on:
  pull_request:
    branches: [ main ]

# Prevent overlapping runs on the same PR/branch (avoids flaky flips)
concurrency:
  group: pr-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-receipt:
    name: Build Tau Receipt
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - uses: actions/checkout@v4

      - name: Emit receipt (PR context)
        shell: bash
        run: |
          set -euo pipefail
          echo '{
            "kind": "tau-crystal-receipt",
            "version": "1",
            "repo": "'"${GITHUB_REPOSITORY}"'",
            "sha": "'"${GITHUB_SHA}"'",
            "run_id": "'"${GITHUB_RUN_ID}"'",
            "runner": "tau-guardian.yml"
          }' > tau-crystal-receipt.json
          cat tau-crystal-receipt.json

      - name: Validate shape
        run: jq -e '.kind=="tau-crystal-receipt"' tau-crystal-receipt.json

      - name: Upload artifact (name must be EXACT)
        uses: actions/upload-artifact@v4
        with:
          name: tau-crystal-manifest
          path: tau-crystal-receipt.json
          if-no-files-found: error

  verify:
    # <<< This job name is the status check name reviewers will see >>>
    name: Tau Crystal Receipt
    runs-on: ubuntu-latest
    needs: build-receipt
    permissions:
      contents: read
      actions: read
    steps:
      - name: Download artifact from this SAME run
        uses: actions/download-artifact@v4
        with:
          name: tau-crystal-manifest
          path: ./artifact

      - name: Verify receipt contents
        shell: bash
        run: |
          set -euo pipefail
          test -s ./artifact/tau-crystal-receipt.json
          jq -e '.kind=="tau-crystal-receipt"' ./artifact/tau-crystal-receipt.json >/dev/null
          echo "Receipt verified"
