name: tau-crystal
on:
  push:
  pull_request:
jobs:
  receipt:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Emit receipt (no-op if script missing)
        shell: bash
        run: |
          if [ -f scripts/emit-receipt.sh ]; then
            bash scripts/emit-receipt.sh
          else
            echo "emit-receipt script not present; skipping"
          fi
      - name: Secondary checker (Python, no-op)
        shell: bash
        run: |
          python3 -V || true
      - name: Upload artifact (if present)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tau-crystal-manifest
          path: .tau_ledger
          if-no-files-found: ignore
