name: tau-test
on:
  push:
    branches: [tau-receipt-test]

jobs:
  attest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: tau
        uses: towre676-cloud/tau-crystal-action@v1
        with:
          working-directory: .
        continue-on-error: true
          if-no-files-found: error
      - name: pick receipt path
        if: always()
        id: pick
        shell: bash
        run: |
          set -uo pipefail
          p="${{ steps.tau.outputs.receipt }}"
          if [ -z "$p" ]; then
            p="$(grep -RIl --include=*.json "merkle_root" . 2>/dev/null | xargs -r grep -Il "chain_head" | head -n1 || true)"
          fi
          echo "using: ${p:-<none>}"
          if [ -n "${p:-}" ]; then echo "path=$p" >> "$GITHUB_OUTPUT"; fi
      - name: upload receipt
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: receipt
          path: ${{ steps.pick.outputs.path }}
          if-no-files-found: warn
