name: tau-test
on:
  push:
    branches: [tau-receipt-test]

jobs:
  attest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: tau
        uses: towre676-cloud/tau-crystal-action@v1
        with:
          working-directory: .
          out: .tau_ledger/receipt.json
        continue-on-error: true
      - name: debug outputs
        if: always()
        run: |
          echo "receipt=${{ steps.tau.outputs.receipt }}"
          echo "chain-head=${{ steps.tau.outputs.chain-head }}"
          echo "merkle-root=${{ steps.tau.outputs.merkle-root }}"
          ls -la . || true
          ls -la .tau_ledger || true
          head -80 .tau_ledger/receipt.json || true
      - name: pick receipt path
        if: always()
        id: pick
        shell: bash
        run: |
          set -uo pipefail
          p="${{ steps.tau.outputs.receipt }}"
          [ -n "$p" ] || p=".tau_ledger/receipt.json"
          # If still missing, try a non-fatal scan
          if [ ! -f "$p" ]; then
            p="$(grep -RIl --include=*.json "merkle_root" . 2>/dev/null | xargs -r grep -Il "chain_head" | head -n1 || true)"
          fi
          echo "using: ${p:-<none>}"
          if [ -n "${p:-}" ]; then echo "path=$p" >> "$GITHUB_OUTPUT"; fi
      - name: upload receipt
        if: always() && steps.pick.outputs.path != 
        uses: actions/upload-artifact@v4
        with:
          name: receipt
          path: ${{ steps.pick.outputs.path }}
          if-no-files-found: warn
