name: tau-automorphic-manual
on:
  workflow_dispatch:
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Hunt zeros & mint new motive
        run: |
          set -Eeuo pipefail
          bash scripts/automorphic/zero_hunt.sh || true
          bash scripts/automorphic/mint_motive.sh $(date +%s) > motive.json
          bash scripts/automorphic/publish_automorphic.sh motive.json || true
      - uses: actions/upload-artifact@v4
        with:
          name: tau-automorphic-artefacts
          path: |
            .tau_ledger/automorphic/new_zeros.json
            .tau_ledger/motives/motive_*.json
