name: tau-test
on:
  push:
    branches: [tau-receipt-test]

jobs:
  attest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: tau
        uses: towre676-cloud/tau-crystal-action@v1
        with:
          working-directory: .
        continue-on-error: true
      - name: pick receipt path
        if: always()
        id: pick
        run: |
          set -euo pipefail
          p="${{ steps.tau.outputs.receipt }}"
          if [ -z "$p" ]; then
            p="$(find "$GITHUB_WORKSPACE" -maxdepth 5 -type f -name "*.json" 2>/dev/null |
                 while read -r f; do grep -q "\"chain_head\"" "$f" && grep -q "\"merkle_root\"" "$f" && echo "$f" && break; done)"
          fi
          echo "using: ${p:-<none>}"
          [ -n "${p:-}" ] && echo "path=$p" >> "$GITHUB_OUTPUT"
      - name: upload receipt
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: receipt
          path: ${{ steps.pick.outputs.path }}
          if-no-files-found: error
