name: tau-test
on:
  push:
    branches: [tau-receipt-test]

jobs:
  attest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: tau
        uses: towre676-cloud/tau_crystal@v1.0.12
        continue-on-error: true
        with:
          working-directory: .
      - name: find receipt path
        if: always()
        id: pick
        run: |
          set -euo pipefail
          p="${{ steps.tau.outputs.receipt }}"
          if [ -z "$p" ]; then
            p="$(find "$GITHUB_WORKSPACE" -maxdepth 4 -type f -name "*.json" 2>/dev/null \\
                | while read -r f; do grep -q '"chain_head"' "$f" && grep -q '"merkle_root"' "$f" && echo "$f" && break; done)
          fi
          echo "using: ${p:-<none found>}"
          [ -n "${p:-}" ] && echo "path=$p" >> "$GITHUB_OUTPUT" || true
      - name: upload receipt
        if: always() && steps.pick.outputs.path != 
        uses: actions/upload-artifact@v4
        with:
          name: receipt
          path: ${{ steps.pick.outputs.path }}
          if-no-files-found: warn
