name: tau-bundled
on:
  push:
    branches: [ tau-verifier-bundled ]
  workflow_dispatch:

jobs:
  attest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # allow later steps to run even if tau fails (we want to see outputs/logs)
      - id: tau
        uses: towre676-cloud/tau-crystal-action@v1
        with:
          working-directory: .
        continue-on-error: true

      - name: debug outputs
        if: always()
        shell: bash
        run: |
          set -euo pipefail
          echo "verifier=${{ steps.tau.outputs.verifier }}"
          echo "receipt=${{ steps.tau.outputs.receipt }}"
          echo "receipt-path=${{ steps.tau.outputs['receipt-path'] }}"
          echo "chain-head=${{ steps.tau.outputs['chain-head'] }}"
          echo "merkle-root=${{ steps.tau.outputs['merkle-root'] }}"

      - id: pick
        name: pick receipt path
        if: always()
        shell: bash
        run: |
          set -euo pipefail
          rp="${{ steps.tau.outputs['receipt-path'] }}"
          [ -z "$rp" ] && rp="${{ steps.tau.outputs.receipt }}"
          [ -z "$rp" ] && rp=".tau_ledger/receipt.json"
          echo "using receipt path: $rp"
          test -f "$rp" || { echo "::error::receipt not found at $rp"; exit 1; }
          echo "rp=$rp" >> "$GITHUB_OUTPUT"

      - id: keys
        name: pick head/root
        if: always()
        shell: bash
        run: |
          set -euo pipefail
          head="${{ steps.tau.outputs['chain-head'] }}"
          root="${{ steps.tau.outputs['merkle-root'] }}"
          [ -z "$head" ] && { echo "::error::missing chain-head output"; exit 1; }
          [ -z "$root" ] && { echo "::error::missing merkle-root output"; exit 1; }
          echo "head=$head" >> "$GITHUB_OUTPUT"
          echo "root=$root" >> "$GITHUB_OUTPUT"

      - name: verify (bundled)
        if: always()
        shell: bash
        run: ${{ steps.tau.outputs.verifier }} \
             "${{ steps.pick.outputs.rp }}" \
             "${{ steps.keys.outputs.head }}" \
             "${{ steps.keys.outputs.root }}"
