name: tau-bundled
on:
  push:
    branches: [ tau-verifier-bundled ]
  workflow_dispatch:

jobs:
  attest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: tau
        uses: towre676-cloud/tau-crystal-action@v1
        with:
          working-directory: .

      - name: debug outputs
        run: |
          echo "verifier=${{ steps.tau.outputs.verifier }}"
          echo "receipt=${{ steps.tau.outputs.receipt }}"
          echo "receipt-path=${{ steps.tau.outputs['receipt-path'] }}"
          echo "chain-head=${{ steps.tau.outputs['chain-head'] }}"
          echo "merkle-root=${{ steps.tau.outputs['merkle-root'] }}"

      - name: pick receipt path
        id: pick
        run: |
          set -euo pipefail
          p="${{ steps.tau.outputs.receipt }}"
          [ -z "$p" ] && p="${{ steps.tau.outputs['receipt-path'] }}"
          if [ -z "$p" ] && [ -f .tau_ledger/CHAIN ]; then
            p="$(awk '{x=$2} END{print x}' .tau_ledger/CHAIN || true)"
          fi
          echo "path=$p" >> "$GITHUB_OUTPUT"

      - name: verify (bundled)
        run: ${{ steps.tau.outputs.verifier }} \
             ${{ steps.pick.outputs.path }} \
             ${{ steps.tau.outputs['chain-head'] }} \
             ${{ steps.tau.outputs['merkle-root'] }}

      - name: upload receipt
        if: ${{ always() && steps.pick.outputs.path != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: receipt
          path: ${{ steps.pick.outputs.path }}
