name: tau-test
on:
  push:
    branches: [tau-receipt-test]

jobs:
  attest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: tau
        uses: towre676-cloud/tau-crystal-action@v1
        continue-on-error: true
        with:
          working-directory: .
      - name: pick receipt path
        if: always()
        id: pick
        run: |
          set -euo pipefail
          p="${{ steps.tau.outputs.receipt }}"
          [ -n "$p" ] || p=".tau_ledger/receipt.json"
          echo "using path: $p"
          echo "path=$p" >> "$GITHUB_OUTPUT"
          test -f "$p" && head -50 "$p" || true
      - name: upload receipt
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: receipt
          path: ${{ steps.pick.outputs.path }}
          if-no-files-found: warn
