name: tau-test
on:
  push:
    branches: [tau-receipt-test]

jobs:
  attest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: tau
        uses: towre676-cloud/tau-crystal-action@v1
        continue-on-error: true
        with:
          working-directory: .
      - name: debug outputs
        if: always()
        run: |
          echo "receipt=${{ steps.tau.outputs.receipt }}"
          test -f "${{ steps.tau.outputs.receipt }}" && head -50 "${{ steps.tau.outputs.receipt }}" || true
      - name: upload receipt
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: receipt
          path: ${{ steps.tau.outputs.receipt }}
          if-no-files-found: error
