name: tau-test
on:
  push:
    branches: [tau-receipt-test]

jobs:
  attest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: tau
        uses: towre676-cloud/tau-crystal-action@v1
        continue-on-error: true
        with:
          working-directory: .
          out: .tau_ledger/receipt.json
      - name: debug ledger
        if: always()
        run: |
          ls -la . || true
          ls -la .tau_ledger || true
          echo "receipt output -> ${{ steps.tau.outputs.receipt }}"
      - name: upload receipt
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: receipt
          path: |
            ${{ steps.tau.outputs.receipt }}
            .tau_ledger/receipt.json
          if-no-files-found: warn
