name: tau-discovery-confirm
on:
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deps
        run: pip install mpmath numpy matplotlib jsonschema
      - name: Confirm double-zero
        run: |
          set -Eeuo pipefail
          python scripts/discovery/confirm_double_zero.py
          python scripts/experimental/stabilize_json.py
      - uses: actions/upload-artifact@v4
        with:
          name: discovery-confirm-witness
          path: |
            .tau_ledger/discovery/confirm_double_zero.json
            .tau_ledger/discovery/confirm_double_zero_stable.json
            .tau_ledger/discovery/plots/*.png
